import Head from "next/head";
import { BsGraphUpArrow } from "react-icons/bs";
import { MdManageHistory } from "react-icons/md";
import { BiSolidNetworkChart } from "react-icons/bi";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { useEffect, useState } from "react";
import Link from "next/link";
import TypingEffect from "@/public/TypingEffect";
import { Fade } from "react-awesome-reveal";

export default function Home() {
  const [images, setImages] = useState([
    "/imagenes/Titulo Bachillerato.png",
    "/imagenes/TOEIC.png",
    "/imagenes/Habilidades blandas.png",
    "/imagenes/Marketing.png",
    "/imagenes/Academy.png",
    "/imagenes/Procesos.png",
  ]);
  const [scrollPosition, setScrollPosition] = useState(0);

  const [color, setColor] = useState(false);

  const settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
  };

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY >= 500) {
        setColor(true);
      } else {
        setColor(false);
      }
    };

    window.addEventListener("scroll", handleScroll);

    // Cleanup the event listener when component is unmounted
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  useEffect(() => {
    const handleScroll = () => {
      setScrollPosition(window.scrollY);
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  const opacity = Math.min(1, Math.max(0, scrollPosition / 100));

  return (
    <>
      <Head>
        <title>Portafolio | Luis Romero</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fotoperfil.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;1,200&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div>
        <div className="">
          <div className="background">
            <div className={color ? "navbarScroll" : "navbar"}>
              <Link href="/">
                <Fade direction="left">
                  <div className="briefCaseIcon">
                    <img src="/imagenes/briefcase.png" width={60} height={60} />
                  </div>
                </Fade>
              </Link>
              <Fade direction="right">
                <div className="navbarlist">
                  <a href="">Inicio</a>
                  <a href="/contacto">Contacto</a>
                </div>
              </Fade>
            </div>
            <TypingEffect text="Portafolio" speed={200}></TypingEffect>
            <div className="info">
              <Fade direction="left">
                <h2>Luis Ernesto Romero</h2>
              </Fade>
              <Fade direction="left">
                <p>Bachiller en Administración de Empresas</p>
              </Fade>

              <Fade direction="right" className="profileImage">
                <div className="profileDesign">
                  <div className="backgrounProfileImage"></div>
                  <div className="backgroundCircle"></div>
                </div>
              </Fade>

              <Fade direction="right">
                <img
                  src="/imagenes/squigly-line.png"
                  className="squigly-line"
                  width={90}
                  height={100}
                />
              </Fade>
              <Fade direction="right">
                <img
                  src="/imagenes/cube.png"
                  className="cube"
                  width={100}
                  height={100}
                />
              </Fade>
              <Fade direction="right">
                <img
                  src="/imagenes/polygon.png"
                  className="polygon"
                  width={100}
                  height={100}
                />
              </Fade>
            </div>
          </div>
        </div>
        <Fade direction="left">
          <div className="aboutme">
            <h2>Acerca de mí</h2>
            <p>
              Me apasionan las tecnologías de la información y la comunicación y
              el análisis financiero. Soy una persona creativa, lo que me ha
              permitido desarrollar habilidades efectivas de liderazgo y
              encontrar soluciones innovadoras. Mi objetivo es seguir creciendo
              en el campo de la administración, aprendiendo de manera continua y
              contribuyendo al éxito de una organización a través de enfoques
              innovadores.
            </p>
          </div>
        </Fade>

        <div className="formacion">
          <div id="educacionInfo">
            <Fade direction="left">
              <h2>Formacion Académica</h2>
            </Fade>

            <Fade direction="left">
              <div className="universidadGroup">
                <h1>Universidad San Marcos (USAM)</h1>
                <p>
                  Licenciatura en Administración de Empresas con énfasis en
                  gerencia
                </p>
                <h3>2023 - Actualmente</h3>
              </div>
            </Fade>

            <Fade direction="left">
              <div className="universidadGroup">
                <h1>Universidad Latina de Costa Rica</h1>
                <p>Administración de Negocios</p>
                <h3>2021 - 2023</h3>
              </div>
            </Fade>

            <Fade direction="left">
              <div className="universidadGroup">
                <h1>Universidad San Marcos (USAM)</h1>
                <p>Técnico en Contabilidad</p>
                <h3>2021 - Incompleto</h3>
              </div>
            </Fade>
          </div>
          <Fade direction="right">
            <div id="circleContainer">
              <div id="circle">
                <img
                  src="/imagenes/graduation-hat.png"
                  width={250}
                  height={250}
                  id="graduaciontHat"
                />
              </div>
            </div>
          </Fade>
        </div>

        <div className="formacion" id="certificado">
          <div id="certificadoInfo">
            <Fade direction="left">
              <h2 id="">Diploma y certificados </h2>
            </Fade>

            <Fade direction="left">
              <div className="universidadGroup">
                <p id="certificadoTitulo">
                  Centro Cultural Costarricense Norteamericano
                </p>
                <p id="certificadoCarrera">TOEIC</p>
                <p id="Certificadofecha">Marzo 2023</p>
              </div>
            </Fade>

            <Fade direction="left">
              <div className="universidadGroup">
                <p id="certificadoTitulo">
                  Transformación Costa Rica y Maxwell Foundation
                </p>
                <p id="certificadoCarrera">Certificado de habilidades Bladas</p>
                <p id="Certificadofecha">Octubre 2022</p>
              </div>
            </Fade>

            <Fade direction="left">
              <div className="universidadGroup">
                <p id="certificadoTitulo">Fundación Carlos Slim</p>
                <p id="certificadoCarrera">Evaluador de Procesos</p>
                <p id="Certificadofecha">Septiembre 2022</p>
              </div>
            </Fade>
            <Fade direction="left">
              <div className="universidadGroup">
                <p id="certificadoTitulo">Google Activate</p>
                <p id="certificadoCarrera">Fundamentos de Marketing Digital</p>
                <p id="Certificadofecha">Septiembre 2021</p>
              </div>
            </Fade>
            <Fade direction="left">
              <div className="universidadGroup">
                <p id="certificadoTitulo">Google Analytics</p>
                <p id="certificadoCarrera">
                  Google Analytics para principiantes
                </p>
                <p id="Certificadofecha">Septiembre 2021</p>
              </div>
            </Fade>
          </div>
          <Fade direction="right">
            <div id="circleContainer">
              <div id="circleOrange">
                <img
                  src="/imagenes/certificate.png"
                  width={150}
                  height={150}
                  id="graduaciontHat"
                />
              </div>
            </div>
          </Fade>
        </div>
        <>
          <>
            <div id="galeriaContacto">
              <Fade direction="left">
                <h2 id="galeriaContactoTitulo">Galeria de fotos</h2>
              </Fade>
              <Slider {...settings} className="sliderImageContacto">
                {images.map((image, index) => (
                  <div key={index} className="carousel-contacto-image">
                    <img
                      src={image}
                      className="imageTituloContacto"
                      alt={`Imagen ${index + 1}`}
                    />
                  </div>
                ))}
              </Slider>
            </div>
          </>
        </>

        <div id="experiencia">
          <Fade direction="left">
            <h2>Experiencia</h2>
          </Fade>
          <div className="experienciaContainer">
            <div className="">
              <Fade direction="left">
                <p id="tituloExperiencia">
                  Voluntariado como asistente administrativo
                </p>
              </Fade>
              <Fade direction="left">
                <p id="experienciaCentro">
                  Centro de Educación Especial Santa Ana (CEESA)
                </p>
              </Fade>
              <Fade direction="left">
                <p id="experienciaFecha">Octubre 2022 - Marzo 2023</p>
              </Fade>
              <Fade direction="left">
                <div className="listExperiencia">
                  <p>
                    • Gestionar el inventario tanto fisico como digital en
                    Excel.
                  </p>
                  <p>
                    • Actualizar periodicamente el inventario en el Sistema de
                    Administración de Bienes (SIAB) de la Junta de Protección
                    Social.
                  </p>
                  <p>
                    • Realizar pedidos mediante el gestor de pedidos del Consejo
                    Nacional de Producción (CNP).
                  </p>
                  <p>
                    • Elaborar las planillas de pagos con los gastos operativos
                    y las deducciones correspondientes.
                  </p>
                  <p> • Realizar cotizaciones</p>
                  <p> • Gestionar archivos.</p>
                </div>
              </Fade>
            </div>
            <Fade direction="right">
              <div id="instalaciones"></div>
            </Fade>
          </div>
          <div id="habilidades">
            <Fade direction="left">
              <h2>Habilidades duras</h2>
            </Fade>
            <div className="habilidadContainer">
              <Fade direction="left">
                <div className="habilidadInfo">
                  <p id="habilitadTituloFinanzas">Finanzas y contabilidad </p>
                  <p>• Estado de resultados</p>
                  <p>• Balance general</p>
                  <p>• Estado de flujo de efectivo</p>
                  <p>• Estado de cambios en el patrimonio</p>
                  <p>• Estado de valor añadido</p>
                  <p>• KPIs financieros</p>
                  <p>• Presupuestación y costo de capital</p>
                  <p>• Proyecciones financieras</p>
                  <span id="graphic">
                    <BsGraphUpArrow />
                  </span>
                </div>
              </Fade>
              <Fade direction="left">
                <div className="habilidadInfo">
                  <p id="habilitadTituloGestion">Gestión empresarial</p>
                  <p>• Gestión de CapEx y OpEx</p>
                  <p>• Planificación estratégica</p>
                  <p>• Metodología Kanban</p>
                  <p>• Balance Scorecard (BSC)</p>
                  <p>• Despliegue de la función de calidad (QFD)</p>
                  <p>• Mezcla de mercadeo</p>
                  <span id="IconGestion">
                    <MdManageHistory />
                  </span>
                </div>
              </Fade>
              <Fade direction="left">
                <div className="habilidadInfo">
                  <p id="habilitadTituloSoftware">
                    Software y herramientas digitales
                  </p>
                  <p>
                    • Sistema de Planificación de Recursos Empresariales (ERP)
                    de Odoo
                  </p>
                  <p>
                    • Microsoft Office (Word, PowerPoint, Teams, Outlook,
                    OneDrive, Excel (Tablas dinámicas, gráficos dinámicos,
                    segmentación de datos)
                  </p>
                  <p>• Trello - Software para la gestión de proyectos</p>
                  <p>• Google Analytics </p>
                  <p>• Google Workspace</p>
                  <p>• Firestore Database</p>
                  <p>• Plataforma de computación en la nube - Firebase</p>
                  <p>• Power BI</p>
                  <p>• Lenguajes de programación (HTML, CSS, Javascript)</p>

                  <span id="network">
                    <BiSolidNetworkChart />
                  </span>
                </div>
              </Fade>
            </div>
          </div>
          <Fade direction="left">
            <div id="idiomas">
              <div className="idiomasBox">
                <h2>Idiomas</h2>
                <p>Inglés: Avanzado</p>
                <p>Escucha: B2</p>
                <p>Hablado: B1</p>
                <p>Lectura: B1</p>
                <p>Escritura: B2</p>
              </div>

              <div className="idiomasBox">
                <h2>Habilidad blandas</h2>
                <p>Empatía</p>
                <p>Trabajo en equipo</p>
                <p>Liderazgo</p>
                <p>Adaptabilidad</p>
                <p>Creatividad</p>
                <p>Innovación</p>
                <p>Comunicación</p>
              </div>
            </div>
          </Fade>
          <div id="footer">
            <Fade direction="left">
              <p>Diseñado por: Luis Ernesto Romero</p>
            </Fade>
          </div>
        </div>
      </div>
    </>
  );
}
