import Head from "next/head";
import { BsGraphUpArrow } from "react-icons/bs";
import { MdManageHistory } from "react-icons/md";
import { BiSolidNetworkChart } from "react-icons/bi";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { useEffect, useState } from "react";
import Link from "next/link";
import TypingEffect from "@/public/TypingEffect";

export default function Home() {
  const [images, setImages] = useState([
    "/imagenes/Titulo Bachillerato.png",
    "/imagenes/TOEIC.png",
    "/imagenes/Habilidades blandas.png",
    "/imagenes/Marketing.png",
    "/imagenes/Academy.png",
    "/imagenes/Procesos.png",
  ]);

  const [color, setColor] = useState(false);

  const settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
  };

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY >= 500) {
        setColor(true);
      } else {
        setColor(false);
      }
    };

    window.addEventListener("scroll", handleScroll);

    // Cleanup the event listener when component is unmounted
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Portafolio | Luis Romero</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fotoperfil.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;1,200&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div>
        <div className="">
          <div className="background">
            <div className={color ? "navbarScroll" : "navbar"}>
              <Link href="/">
                <div className="briefCaseIcon">
                  <img src="/imagenes/briefcase.png" width={60} height={60} />
                </div>
              </Link>
              <div className="navbarlist">
                <a href="">Inicio</a>
                <a href="/contacto">Contacto</a>
              </div>
            </div>
            <>
              <TypingEffect text="Portafolio" speed={200}></TypingEffect>
            </>
            <div className="info">
              <>
                <h2>Luis Ernesto Romero</h2>
              </>
              <>
                <p>Bachiller en Administración de Empresas</p>
              </>
              <>
                <div className="profileImage">
                  <div className="profileDesign">
                    <div className="backgrounProfileImage"></div>
                    <div className="backgroundCircle"></div>
                  </div>
                </div>
              </>
              <img
                src="/imagenes/squigly-line.png"
                className="squigly-line"
                width={90}
                height={100}
              />
              <img
                src="/imagenes/cube.png"
                className="cube"
                width={100}
                height={100}
              />
              <img
                src="/imagenes/polygon.png"
                className="polygon"
                width={100}
                height={100}
              />
            </div>
          </div>
        </div>
        <>
          <div className="aboutme">
            <h2>Acerca de mí</h2>
            <p>
              Me apasionan las tecnologías de la información y la comunicación y
              el análisis financiero. Soy una persona creativa, lo que me ha
              permitido desarrollar habilidades efectivas de liderazgo y
              encontrar soluciones innovadoras. Mi objetivo es seguir creciendo
              en el campo de la administración, aprendiendo de manera continua y
              contribuyendo al éxito de una organización a través de enfoques
              innovadores.
            </p>
          </div>
        </>

        <div className="formacion">
          <>
            <h2>Formacion Académica</h2>
          </>
          <>
            <div>
              <p id="nombreuniversidad">Universidad San Marcos (USAM)</p>
              <p id="universidad">
                Licenciatura en Administración de Empresas con énfasis en
                gerencia
              </p>
              <p id="fecha">2023 - Actualmente</p>
            </div>
          </>
          <>
            <div>
              <p id="nombreuniversidad">Universidad Latina de Costa Rica</p>
              <p id="universidad">Administración de Negocios</p>
              <p id="fecha">2021 - 2023</p>
            </div>
          </>
          <>
            <div>
              <p id="nombreuniversidad">Universidad San Marcos (USAM)</p>
              <p id="universidad">Técnico en Contabilidad</p>
              <p id="fecha">2021 - Incompleto</p>
            </div>
          </>
          <>
            <div className="birrete">
              <div id="parallelogram"></div>
              <img
                src="/imagenes/graduation-hat.png"
                width={250}
                height={250}
                id="graduaciontHat"
              />
            </div>
          </>
        </div>

        <div className="certificados">
          <>
            <h2>Título y Certificados</h2>
          </>
          <>
            <div>
              <p id="nombreuniversidad">
                Centro Cultural Costarricense Norteamericano
              </p>
              <p id="certificadoNombre">TOEIC</p>
              <p id="fecha">Marzo, 2023</p>
            </div>
          </>
          <>
            <div>
              <p id="nombreuniversidad">
                Transformación Costa Rica y Maxwell Foundation
              </p>
              <p id="universidad">Certificado de Habilidades Blandas</p>
              <p id="fecha">Octubre, 2022</p>
            </div>
          </>
          <>
            <div>
              <p id="nombreuniversidad">Fundación Carlos Slim</p>
              <p id="universidad">Evaluador de Procesos</p>
              <p id="fecha">Septiembre, 2022</p>
            </div>
          </>
          <>
            <div>
              <p id="nombreuniversidad">Google Activate</p>
              <p id="universidad">Fundamentos de Marketing Digital</p>
              <p id="fecha">Septiembre, 2021</p>
            </div>
          </>
          <>
            <div>
              <p id="nombreuniversidad">Fundación Carlos Slim</p>
              <p id="universidad">Programa de educación financiera</p>
              <p id="fecha">Septiembre, 2021</p>
            </div>
          </>
          <>
            <div>
              <p id="nombreuniversidad">Google Analytics Academy</p>
              <p id="universidad">Google Analytics para Principiantes</p>
              <p id="fecha">Febrero, 2021</p>
            </div>
          </>
          <>
            <div className="birrete">
              <div id="burst-12"></div>
              <img
                src="/imagenes/certificate.png"
                width={200}
                height={200}
                id="certificationImage"
              />
            </div>
          </>
        </div>

        <>
          <div id="galeria">
            <h2>Galeria de fotos</h2>
            <Slider {...settings} className="sliderImage">
              {images.map((image, index) => (
                <div key={index} className="carousel-image">
                  <img
                    src={image}
                    className="imageTitulo"
                    alt={`Imagen ${index + 1}`}
                  />
                </div>
              ))}
            </Slider>
          </div>
        </>

        <div id="experiencia">
          <>
            <h2>Experiencia</h2>
          </>
          <div className="experienciaContainer">
            <div className="">
              <>
                <p id="tituloExperiencia">
                  Voluntariado como asistente administrativo
                </p>
              </>
              <>
                <p id="experienciaCentro">
                  Centro de Educación Especial Santa Ana (CEESA)
                </p>
              </>
              <>
                <p id="experienciaFecha">Octubre 2022 - Marzo 2023</p>
              </>
              <>
                <div className="listExperiencia">
                  <p>
                    • Gestionar el inventario tanto fisico como digital en
                    Excel.
                  </p>
                  <p>
                    • Actualizar periodicamente el inventario en el Sistema de
                    Administración de Bienes (SIAB) de la Junta de Protección
                    Social.
                  </p>
                  <p>
                    • Realizar pedidos mediante el gestor de pedidos del Consejo
                    Nacional de Producción (CNP).
                  </p>
                  <p>
                    • Elaborar las planillas de pagos con los gastos operativos
                    y las deducciones correspondientes.
                  </p>
                  <p> • Realizar cotizaciones</p>
                  <p> • Gestionar archivos.</p>
                </div>
              </>
            </div>
            <>
              <div id="instalaciones"></div>
            </>
          </div>
          <div id="habilidades">
            <>
              <h2>Habilidades duras</h2>
            </>
            <div className="habilidadContainer">
              <>
                <div className="habilidadInfo">
                  <p id="habilitadTituloFinanzas">Finanzas y contabilidad </p>
                  <p>• Estado de resultados</p>
                  <p>• Balance general</p>
                  <p>• Estado de flujo de efectivo</p>
                  <p>• Estado de cambios en el patrimonio</p>
                  <p>• Estado de valor añadido</p>
                  <p>• KPIs financieros</p>
                  <p>• Proyecciones financieras</p>
                  <p>• Proyecciones de inversión</p>
                  <span id="graphic">
                    <BsGraphUpArrow />
                  </span>
                </div>
              </>
              <>
                <div className="habilidadInfo">
                  <p id="habilitadTituloGestion">Gestión empresarial</p>
                  <p>• Gestión de CapEx y OpEx</p>
                  <p>• Planificación estratégica</p>
                  <p>• Metodología Kanban</p>
                  <p>• Balance Scorecard (BSC)</p>
                  <p>• Despliegue de la función de calidad (QFD)</p>

                  <span id="IconGestion">
                    <MdManageHistory />
                  </span>
                </div>
              </>
              <>
                <div className="habilidadInfo">
                  <p id="habilitadTituloSoftware">
                    Software y herramientas digitales
                  </p>
                  <p>
                    • Sistema de Planificación de Recursos Empresariales (ERP)
                    de Odoo
                  </p>
                  <p>
                    • Microsoft Office (Word, PowerPoint, Teams, Outlook,
                    OneDrive, Excel (Tablas dinámicas, gráficos dinámicos,
                    segmentación de datos)
                  </p>
                  <p>• Trello </p>
                  <p>• Google Analytics </p>
                  <p>• Google Workspace</p>
                  <p>• Firebase </p>
                  <p>• Power BI</p>
                  <p>• Lenguajes de programación (HTML, CSS, Javascript)</p>

                  <span id="network">
                    <BiSolidNetworkChart />
                  </span>
                </div>
              </>
            </div>
          </div>
          <div id="idiomas">
            <div className="idiomasContainer">
              <>
                <div className="idiomasBox">
                  <h2>Idiomas</h2>
                  <p>Inglés: Avanzado</p>
                  <p>Escucha: B2</p>
                  <p>Hablado: B1</p>
                  <p>Lectura: B1</p>
                  <p>Escritura: B2</p>
                </div>
              </>
              <>
                <div className="idiomasBox">
                  <h2>Habilidad blandas</h2>
                  <p>Empatía</p>
                  <p>Trabajo en equipo</p>
                  <p>Liderazgo</p>
                  <p>Adaptabilidad</p>
                  <p>Creatividad</p>
                  <p>Innovación</p>
                  <p>Comunicación</p>
                </div>
              </>
            </div>
          </div>
          <div id="footer">
            <>
              <p>Diseñado por: Luis Ernesto Romero</p>
            </>
          </div>
        </div>
      </div>
    </>
  );
}
